### ISSUE TITLE
newb question - translation of flex css to bs-css

### ISSUE THREAD

**Issue by webern** [SentiaAnalytics/bs-css#161]
I can't understand how to translate a certain flexbox css construct into bs-css

For example, this:

```css
.col-1 {
  background: #D7E8D4;
  flex: 1;
}
```

This is a type error:

```reasonml
let col1 = style([
	  background(hex("#D7E8D4")),
	  flex(1.),
	]);
```

This is a type error:

```reasonml
let col1 = style([
	  background(hex("#D7E8D4")),
	  flex(1),
	]);
```

How can I express the original css in bs-css?
